version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - .*
      exclude:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: crpi-ysk9v7z15tyb8r02.cn-hangzhou.personal.cr.aliyuncs.com/ysl_1/ai_dhlr
        username: 是小杨同志
        password: 20020114..
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: true
        processorType:
          - arm64
        parameter: {}
        notify: []
        strategy:
          retry: '0'
